var adapter = require('./adapter')
global.adapter = adapter

// require('./aplus-tests/2.1.2')
// require('./aplus-tests/2.1.3')
require('./aplus-tests/2.2.1')
// require('./aplus-tests/2.2.2')
// require('./aplus-tests/2.2.3')
// require('./aplus-tests/2.2.4')
// require('./aplus-tests/2.2.5')
// require('./aplus-tests/2.2.6')
// require('./aplus-tests/2.2.7')
// require('./aplus-tests/2.3.1')
// require('./aplus-tests/2.3.2')
// require('./aplus-tests/2.3.3-part1')
// require('./aplus-tests/2.3.3-part2')
// require('./aplus-tests/2.3.3-part3')
// require('./aplus-tests/2.3.3-part4')
// require('./aplus-tests/2.3.4')
